# Password Cracking Practice Scripts
## About
This collection of scripts can be used in order to generate practice password cracking in order to practice using tools such as [Hashcat](https://github.com/hashcat/hashcat) and [John The Ripper](https://github.com/openwall/john). 

Currently, this repo contains five scripts:
 * `gen_hashes.sh <wordlist>` - Generates five password hashes based on entries in the provided wordlist.
 * `gen_padded_hashes.sh <wordlist>` - Generates five password hashes based on entires in the provided wordlist, right-padding each password with one to four random digits. 
 * `gen_combo_hashes.sh <wordlist>` - Generates five password hashes based on combining two seperate lines from the provided wordlist.
 * `gen_random_hashes.sh` - Generates five random password hashes each comprised of five random uppercase or lowercase letters.
 * `gen_random_lc_hashes.sh` - Generates five random password hashes each comprised of five lowercase letters.
 
In order to use these scripts you must have a wordlist such as [rockyou.txt](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Leaked-Databases/rockyou.txt.tar.gz) (Kali users can find wordlists in /usr/share/wordlists/).

## Usage
Each script will output hashes to STDOUT and notification information to STDERROR. In order to use the hashes generated by this script redirect the output using the `>` operator. Example: `bash gen_hashes.sh /path/to/wordlist.txt > target_hashes.txt`

### Examples
Scripts requiring a wordlist:
```
[user@host ~]$ ./gen_hashes.sh /usr/share/wordlists/rockyou.txt > target_hashes.txt
Generating '684f83bc712d19916da8b21981ebedc09e17adff' from 'fate538'
Generating 'd30aa3eef7e42ba30333a452af0e2d60f4fc1eef' from '@#dancer77'
Generating '1f7f3b0c32b1f59aa6bed988eb151778b05080c8' from 'japopoy'
Generating '2557f23b28eef1c00a896cc7b80db104d5c92e9e' from '0281324853'
Generating '44c08c3b071fa0a22018d4423db140e79c920613' from 'khrystle1'

[user@host ~]$ cat target_hashes.txt 
684f83bc712d19916da8b21981ebedc09e17adff
d30aa3eef7e42ba30333a452af0e2d60f4fc1eef
1f7f3b0c32b1f59aa6bed988eb151778b05080c8
2557f23b28eef1c00a896cc7b80db104d5c92e9e
44c08c3b071fa0a22018d4423db140e79c920613
```

Scripts that don't require a wordlist:
```
[user@host ~]$ ./gen_random_hashes.sh > target_hashes.txt
Generating '17a04d8e2355f087e08e51b40fef1bc8e03af237' from 'ifnXW'.
Generating 'cd291910b6e2bfea4a9e32c3cc190869f2399264' from 'cdJff'.
Generating '091857c85188f6f3e747a404592363615c71acb9' from 'qLOow'.
Generating '823039c63cc969cd91b835b40ea8d7c8752c6976' from 'oBPAH'.
Generating '3483c1a1fd74a5657b1e9fc07e08a0c9bdc4aba9' from 'ebNaC'.

[user@host ~]$ cat target_hashes.txt 
17a04d8e2355f087e08e51b40fef1bc8e03af237
cd291910b6e2bfea4a9e32c3cc190869f2399264
091857c85188f6f3e747a404592363615c71acb9
823039c63cc969cd91b835b40ea8d7c8752c6976
3483c1a1fd74a5657b1e9fc07e08a0c9bdc4aba9
```
